[package]
name = "hc_utils"
version = "0.1.0"
authors = ["zo-el <joel.ulahanna@holo.host>"]
edition = "2018"

[dependencies]
serde = "=1.0.104"
# hdk3 = { path = "../../../holochain/crates/hdk" }
hdk3 = { git = "https://github.com/holochain/holochain.git", rev = "6521474d854a13dba71daa1d73779a7a70341da0", package = "hdk3" }
# hdk3 = { git = "https://github.com/holochain/holochain.git", branch = "develop" }
# holo_hash = { path = "../../../holochain/crates/holo_hash" }
holo_hash = { git = "https://github.com/holochain/holochain.git", rev = "6521474d854a13dba71daa1d73779a7a70341da0", package = "holo_hash" }
thiserror = "1.0.20"

[lib]
name = "hc_utils"
path = "src/lib.rs"
# "cargo test --doc" doctests are not performed with the "cdylib" crate-type
crate-type = ["cdylib", "rlib"]
